version: "3"

services:
  flask:
    build:
      context: ./
      dockerfile: container/docker/flask/Dockerfile
    container_name: 'flask-docker'
    volumes:
      - ./container/flask:/application
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    volumes:
      - app_db:/var/lib/mysql
      - ./shop.sql:/docker-entrypoint-initdb.d/init-database.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
    ports:
      - "3306:3306"


networks:
  app:
    driver: bridge

volumes:
  app_db: