version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    container_name: 'app-docker'
    volumes:
      - .:/application
    ports:
      - "8080:8080"
