version: "3"

services:
  flask:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    container_name: 'flask-docker'
    volumes:
      - .:/flask
    ports:
      - "8080:8080"
